//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortKnox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxFK
    {
        public System.Guid IdTxFK { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public decimal MontoFiscal { get; set; }
        public string Usuario { get; set; }
        public decimal MontoOperacion { get; set; }
    }
}
